<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <title>HTML.PHP</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
  <style>
    body {
      margin:0;
      font-family: "Comic Neue", cursive, sans-serif;
      font-weight: 700;
      background: url('https://www.transparenttextures.com/patterns/asfalt-dark.png');
      color:#fff;
      text-align:center;
    }
    .container {
      max-width: 600px;
      margin: 2rem auto;
      background: rgba(0, 0, 0, 0.07);
      padding: 2rem;
      border: 3px solid #ff00aa;
      border-radius: 10px;
    }
    h1 {
      font-weight: 700;
      font-size:3rem;
      color:yellow;
      text-shadow:2px 2px 0 #000, 0 0 10px #ff00aa;
      margin-top:2rem;
    }
    p {
      color:rgb(56, 36, 122);
      font-size:1.2rem;
      margin:1rem 0;
    }
    img {
      margin-top:1rem;
      border:5px ridge #ff00aa;
      max-width:300px;
    }
    .back-link {
            display: inline-block;
            background: rgb(21, 255, 0);
            margin-top: 1rem;
            color:rgb(0, 0, 0);
            text-decoration: none;
            border: 2px solid rgb(21, 255, 0);
            padding: 10px 20px;
            font-weight: 700;
        }
        .back-link:hover {
            background: rgb(252, 248, 17);
            border: 2px solid rgb(252, 248, 17);
            color: #000000;
      }
  </style>
</head>
<body>
  <h1 id="title">★ Trying to do some HTML with CGI ★</h1>
  <img id="image" src="https://ichef.bbci.co.uk/ace/standard/1800/cpsprodpb/18d0/live/88ff5600-d979-11ef-a5c8-1da73bd59591.jpg" alt="Dog sleeping">

  <div class="container">
    <?php
		// En-tête HTTP obligatoire pour CGI
		header("Content-Type: text/html; charset=UTF-8");


		// Contenu HTML
		echo "<!DOCTYPE html>";
		echo "<html lang='fr'>";
		echo "<head>";
		echo "<meta charset='UTF-8'>";
		echo "<title>Test PHP CGI</title>";
		echo "</head>";
		echo "<body>";
		echo "<p>Hello from CGI PHP!</h1>";
		echo "<p>This sentence in HTML was generated by a CGI script.</p>";
		echo "</body>";
		echo "</html>";
	?>
  </div>

  <p id="message">It's ugly, right?</p>
  <a href="/cgi.html" class="back-link">← Go back to the CGI page</a>
</body>
</html>
