#!/usr/bin/php-cgi
<?php
// Définir le type de contenu (ne pas ajouter \r\n\r\n ici)
header("Content-Type: text/html; charset=UTF-8");

// Exemple de variables PHP utiles
$server = $_SERVER['SERVER_SOFTWARE'] ?? 'Serveur inconnu';
$time   = date("Y-m-d H:i:s");

echo "<h1>★ Page generated by PHP CGI ★</h1>\n";
echo "<p><strong>Server's hour :</strong> $time</p>\n";
echo "<p>This simple test shows that our webserv is handling CGI with PHP.</p>\n";

echo '
    <style>
      @font-face {
        font-family: "ComicNeue";
        src: url("/fonts/ComicNeue-Regular.otf") format("opentype");
        font-weight: 400;
        font-style: normal;
      }
      body{
        margin:0;
        font-family: "ComicNeue", cursive, sans-serif;
        font-weight: 700;
        background: url("https://www.transparenttextures.com/patterns/asfalt-dark.png");
        text-align:center;
      }
      h1 {
        font-weight: 700;
        font-size:3rem;
        color:yellow;
        text-shadow:2px 2px 0 #000, 0 0 10px #ff00aa;
        margin-top:2rem;
      }
    </style>
    <p><a href="/cgi.html" 
    style="
    display:inline-block;
    padding:10px 20px;
    background-color:#21ff00;
    color:#000;
    text-decoration:none;
    font-weight:bold;
    border:2px solid #21ff00;
    border-radius:5px;"
    >← Go back to the CGI page</a></p>';
?>

